### ISSUE TITLE
LLM Strategy

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#10]
Sub 

- [x] [LLM Strategy 1: Build our falcon model](https://github.com/ttt246/Brain/issues/8)
- [x] [LLM Strategy 2: Implement AutoGPT](https://github.com/ttt246/Brain/issues/7)
- [x] [LLM Strategy 3: Implement an interface to configure model](https://github.com/ttt246/Brain/issues/9)

Cc: @posix4e @tukpsyche

**Comment by stackdev37** [comment]
It includes autogpt and it will be done in the next milestones(9, 10)

**Comment by stackdev37** [comment]
Autogpt task dependency: 
https://github.com/ttt246/Brain/issues/9
