### ISSUE TITLE
Document Management

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#146]
We need to follow the below step with Akito

- [ ] 1. [Onboard with Brain#143](https://github.com/ttt246/Brain/issues/143)

- [ ] 2. [Clean all readme in Brain#144](https://github.com/ttt246/Brain/issues/144)

- [ ] 3. [Implement Git Wiki Web Page for Brain#145](https://github.com/ttt246/Brain/issues/145)
