### ISSUE TITLE
Design Stuff Management

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#235]
Sub Tasks:

- [ ] 1. [Design Web Site#231](https://github.com/ttt246/Brain/issues/231)

- [ ] 2. [Design Android App#232](https://github.com/ttt246/Brain/issues/232)

- [ ] 3. [iOS Apps Design#233](https://github.com/ttt246/Brain/issues/233)

- [ ] 4. [Extension Design#234](https://github.com/ttt246/Brain/issues/234)
